### PR TITLE
docs: add DocC API documentation

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Issue Description

Starting from Xcode 13, [DocC](https://developer.apple.com/documentation/docc) can be used to build documentation natively. These make the docs look exactly look like the apple docs along with enabling the addition of [interactive tutorials](https://developer.apple.com/documentation/docc/tutorial-syntax). Tutorials can be created easily from the Playground code, though screenshots will need to be added to the tutorial assets to make them look nice.

Related issue: #n/a

### Approach

- Add DocC docs for the SDK
- Keep Jazzy for now as DocC doesn't work with static Github Pages. Static pages will be supported when Swift 5.6 is released

### TODOs before merging

- [x] add DocC build to CI
- [x] add change log

### CODE REVIEW

**Comment by cbaker6** [comment]
@TomWFox this should make the docs look even nicer and once some of the interactive tutorials are added from the Playgrounds allow linking to blogs, etc. The tutorials are pretty easy to make and will look like: https://developer.apple.com/tutorials/SwiftUI

I've attempted to make this release to the current documentation link, though we will need to test this some to see if it works.

Let me know what you think.

**Comment by TomWFox** [comment]
This looks great, thanks for all the insightful info. I'm looking forward to interactive tutorials!

**Review by TomWFox — APPROVED** [review]

**Comment by cbaker6** [comment]
@TomWFox I tried this out on one of my personal repo's and it seems there's some additional work we need to figure out with GitHub Pages to get this to show the documentation. I think it has something to do with finding the equivalent to:

```
# Enable custom routing.
RewriteEngine On

# Route documentation and tutorial pages.
RewriteRule ^(documentation|tutorials)\/.*$ ParseSwift.doccarchive/index.html [L]

# Route files and data for the documentation archive.
#
# If the file path doesn't exist in the website's root ...
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# ... route the request to that file path with the documentation archive.
RewriteRule .* ParseSwift.doccarchive/$0 [L]
```

In Jekyll, https://developer.apple.com/documentation/Xcode/distributing-documentation-to-external-developers

**Comment by TomWFox** [comment]
Hmm, I did some reading and it seems it’s not currently possible to host DocC as a static site for GitHub pages. This post was insightful https://www.jessesquires.com/blog/2021/06/29/apple-docc-great-but-useless-for-oss/ - there was a reference to a post about converting the archive to a static site but I would imagine that could be a janky solution.

It seems straight forward to host DocC on Netlify or similar but it wouldn’t be ideal to loose the simplicity of gh pages.

We may have to wait to see how things develop here.

**Comment by cbaker6** [comment]
Great find! From the article, they linked to a tweet which mentions DocC may eventually be hosted by Swift Package Index which would make for an easy process https://twitter.com/_sa_s/status/1410155365270966274?s=21

**Pull request merged**
