### PR TITLE
Fix SPM Issue: Remove duplicate playground page

### LINKED ISSUE #68: SPM Broken on v1.1.0+ and branch main
Today, I pulled the latest version of Parse-Swift and it crashes Xcode.  This did not happen yesterday.  It happens for versions branch main, 1.1.0 and greater.  Oddly, I thought I pulled v1.1.2 earlier but could be wrong.  Other SPM packages are pulled down without issue.

**DO NOT TEST THIS ON A PROJECT YOU CARE ABOUT.  CREATE A TEST PROJECT.  THE PROJECT GOES INTO A CRASH LOOP.**
Steps to reproduce:
1) Create new iOS app.
2) Add Parse-Swift package with versions from branch main, 1.1.0, or 1.1.2 in SPM.
3) Xcode crashes as it pulls down the library.

@cbaker6 For some reason, I thought these versions were working earlier with SPM.  Any ideas?

### PR DESCRIPTION
**Pull request by pmmlo**
- Remove playground duplicate line: `<page name='10 - Cloud Code'/>`

Fix #68

### CODE REVIEW

**Comment by pmmlo** [comment]
@cbaker6 This is pretty funny, if it works.  Could you try this?

**Comment by cbaker6** [comment]
This works!

**Comment by cbaker6** [comment]
We will need to release a new version in order to not have people download the broken one

**Comment by pmmlo** [comment]
Cheers!  Whatever you think is best.  It'd be really cool, if you could push it tonight.  I'm playing around with CloudCode for the first time in a while and wanted to test it out on the latest!

You can also merge the fix yourself and close this PR, if that'll make things go faster.  I don't care for the credit and you've done all the work.

**Comment by cbaker6** [comment]
@pmmlo are you good with your name in the changelog? That's what I see on Github. Feel free to change it if you want.

**Comment by pmmlo** [comment]
> @pmmlo are you good with your name in the changelog? That's what I see on Github. Feel free to change it if you want.

It'd be cool if it weren't included, but not a big deal at the end of the day. 

Serious thanks for all of your work and all.  Also, huge congrats on v1.0.0!  This SDK sat experimental for ages.  You're a rockstar.

**Comment by cbaker6** [comment]
> Serious thanks for all of your work and all. Also, huge congrats on v1.0.0! This SDK sat experimental for ages. You're a rockstar.
🙏🏿

**Pull request merged**
