### PR TITLE
fix: add barrier for thread safety

### PR DESCRIPTION
**Pull request by vdkdamian**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Issue Description
This fixes an issue when downloading or uploading multiple items in ParseSwift that was caused by a thread-safety issue.

Related issue: #347

### Approach
This PR adds a barrier to fix the related issue

### TODOs before merging

- [ ] Add entry to changelog
- [x] Lint

### CODE REVIEW

**Comment by vdkdamian** [comment]
@cbaker6 Why are the checks failing?

**Comment by cbaker6** [comment]
> @cbaker6 Why are the checks failing?

Not sure, maybe you can set break points on the failing tests and your changes to determine where the failures are coming from?

**Comment by vdkdamian** [comment]
> Not sure, maybe you can set break points on the failing tests and your changes to determine where the failures are coming from?

It's coming from the test `[ParseSwiftTests.ParseFileAsyncTests testFetchFileProgress]`.
Schermafbeelding 2022-03-03 om 19 32 34

**Comment by cbaker6** [comment]
@vdkdamian can you try the latest branch in your code to see if you still run into the crash in your app?

**Comment by vdkdamian** [comment]
> @vdkdamian can you try the latest branch in your code to see if you still run into the crash in your app?

Yes, the crash is back.
Schermafbeelding 2022-03-05 om 08 23 07

**Review by arihantthriwe — APPROVED** [review]

**Comment by cbaker6** [comment]
Closing in favor of #394

**Pull request closed without merging**
