### PR TITLE
Fix server responses and saving of ParseObjects

### PR DESCRIPTION
**Pull request by cbaker6**
- [x] show fetching example of server updates not being saved on local device ([commit](https://github.com/parse-community/Parse-Swift/pull/34/commits/da6f377125a0bd303a443578c908708ac9c00717)). Fixed by removing `FetchResponse` ([commit](https://github.com/parse-community/Parse-Swift/pull/34/commits/63c0df27e8a190bc4b9212a12e3fb0b0be0dc802))
- [x] persist server response of all `ParseObjects` during  `fetch` and `fetchAll`. `fetchAll` in the JS and Objc API's query for fetch based on a list of `objectIds`. Parse-Swift does the samething now. `FetchResponse` was deleted as it's not needed and isn't versatile enough to support all `ParseObjects`. 
- [x] add `deleteAll`
- [x] add/tested playgrounds examples of sync/async: fetch, fetchAll, deleteAll 
- [x] clean up CI

### CODE REVIEW

**Comment by cbaker6** [comment]
@TomWFox can you look over the docs and some of the `throw` errors I added? I particularly added new documentation for `deleteAll` and added warnings to both `fetchAlls`.

**Comment by cbaker6** [comment]
@pranjalsatija can you review this?

**Review by TomWFox — APPROVED** [review]
Docs look good 👍

**Comment by cbaker6** [comment]
@TomWFox can you change the branch protections from "deploy_docs" to "docs"?

**Pull request merged**
