### PR TITLE
fix: check for ParseError first after server response

### LINKED ISSUE #313: Response parsing error when ParseUser is successfully signed up
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

When sining up a User Parse sever response may not contain a sessionToken (Parse 4.2)

### Steps to reproduce

- Create a ParseUser subclass

```swift
import Foundation
import ParseSwift
​
struct User: ParseUser {
    var emailVerified: Bool?
    var password: String?
    var authData: [String: [String: String]?]?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
​
    public var objectId,
			   email,
               qrCode:         String?
​
​
}
```

- Uses one of the ParseUser methods to sign up an instance ()

```swift
var user = User();
                   user.password = password;
                   user.username = username;
                   user.email = email;
                   user.qrCode = "";
            
user.signup() { result in
    switch result {
    case .failure(let error):
        //: Publish error.
        self.error = error
        print(error.message)
    case .success(user):
        print("Successfully queried data")
    case .success(_):
        print("Successfully queried data")
    }
}
```
or
```swift
var user = User();
                   user.password = password;
                   user.username = username;
                   user.email = email;
                   user.qrCode = "";
            
let publisher = user
    .signupPublisher()
        .sink(
                receiveCompletion: { result in
                    switch result {
                    case .failure(let error):
                        //: Publish error.
                        self.error = error
                        print(error.message)
                    case .finished:
                        print("Successfully queried data")
                    }
                }, receiveValue: { user in
                    self.user = user
                }
        )
publisher.store(in: &subscriptions)
```

### Actual Outcome
Subscription results as an unknown error but the ParseUser is stored in database

### Expected Outcome
Returns a success or an explaination on why the outcome is an error

### Environment

Client
- Parse Swift SDK version: `3.0.0`
- Xcode version: `13.2.1`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: ` 13-15`

Server
- Parse Server version: `4.2.0`
- Operating system: `N/A`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Back4App`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Back4App`

### Logs
```
(ParseSwift.ParseError) error = {
  code = unknownError {}
  message = "Invalid struct: No value associated with key CodingKeys(stringValue: \"sessionToken\", intValue: nil) (\"sessionToken\")."
  otherCode = nil {
    some = (_value = 0)
  }
}
```

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Issue Description

Currently tries to decode response as object before checking for error.

Related issue: #313

### Approach

Always check if an error can be decoded first.

### TODOs before merging

- [x] Check CI passes

### CODE REVIEW

**Comment by cbaker6** [comment]
@Climbatize @vdkdamian can you check if this branch solves the problem?

**Comment by vdkdamian** [comment]
> @Climbatize @vdkdamian can you check if this branch solves the problem?
> 
> Also check if all other functionality works as normal. I'll take a further look later...

I'll adopt to this branch now, and let you know in the next few days if any of the testers experienced issues.

**Comment by cbaker6** [comment]
Tested this on all of the playground examples and it works. The change makes sense logically and should be fine to add as `ParseObject`'s don't look like `ParseError`'s.

**Comment by vdkdamian** [comment]
@cbaker6  I currently haven't experienced any issues with the change either. LGTM

**Comment by cbaker6** [comment]
@vdkdamian thanks for checking!

**Comment by MergeMaster** [comment]
I am still getting this error using ParseSwift 4.12.2 and ParseServer 5.4.0. In the server `preventLoginWithUnverifiedEmail` and `verifyUserEmails` are set to `true`. The error that I am getting is the one of #313. 

Should I create a new issue? @cbaker6

**Pull request merged**
